export const UPLOADING_INPUT_DATA = 'UPLOADING_INPUT_DATA'
export const UPLOADING_INPUT_DATA_SUCCESS = 'UPLOADING_INPUT_DATA_SUCCESS'
export const UPLOADING_INPUT_DATA_FAILED = 'UPLOADING_INPUT_DATA_FAILED'

export const CLEAR_ALL = 'CLEAR_ALL'
export const ADD_TRANSFORM = 'ADD_TRANSFORM'
export const MOVE_TRANSFORM = 'MOVE_TRANSFORM'
export const ADD_TRANSFORM_TO_MLA = 'ADD_TRANSFORM_TO_MLA'
export const REMOVE_TRANSFORM_FROM_MLA = 'REMOVE_TRANSFORM_FROM_MLA'
export const APPLY_TRANSFORM_SETTINGS = 'APPLY_TRANSFORM_SETTINGS'
export const GET_TRANSFORM_DATA_START = 'GET_TRANSFORM_DATA_START'
export const GET_TRANSFORM_DATA_SUCCESS = 'GET_TRANSFORM_DATA_SUCCESS'
export const GET_TRANSFORM_DATA_FAILED = 'GET_TRANSFORM_DATA_FAILED'
export const SELECT_TRANSFORM = 'SELECT_TRANSFORM'
export const REMOVE_TRANSFORM = 'REMOVE_TRANSFORM'


export const TRAIN_AND_TEST_STARTED = 'TRAIN_AND_TEST_STARTED'
export const TRAIN_AND_TEST_SUCCESS = 'TRAIN_AND_TEST_SUCCESS'
export const TRAIN_AND_TEST_FAILED = 'TRAIN_AND_TEST_FAILED'


export const OPTIMIZER_OPENED = 'OPTIMIZER_OPENED'
export const OPTIMIZER_STARTED = 'OPTIMIZER_STARTED'
export const OPTIMIZER_FINISHED = 'OPTIMIZER_FINISHED'
export const OPTIMIZER_FAILED = 'OPTIMIZER_FAILED'
export const OPTIMIZER_CLOSED = 'OPTIMIZER_CLOSED'

export const TRAINER_LOAD_SETTINGS = 'TRAINER_LOAD_SETTINGS'
export const TRAINER_SAVE_SETTINGS = 'TRAINER_SAVE_SETTINGS'
export const TRAINER_STARTED = 'TRAINER_START'
export const TRAINER_FINISHED = 'TRAINER_FINISHED'
export const TRAINER_FAILED = 'TRAINER_FAILED'

export const TASK_CREATED = 'TASK_CREATED'
export const TASK_FINISHED = 'TASK_FINISHED'
export const TASK_TIMEOUT = 'TASK_TIMEOUT'
export const TASK_CANCELED = 'TASK_CANCELED'
export const TASK_FAILED = 'TASK_FAILED'

export const SET_CHART_DATA = 'SET_CHART_DATA'
export const GET_CHART_DATA = 'GET_CHART_DATA'

export const SET_METRIC_DATA = 'SET_METRIC_DATA'
export const GET_METRIC_DATA = 'GET_METRIC_DATA'